name: Publish

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: make owner lowercase
        run: echo "${{ env.OWNER }}" | awk '{print tolower($0)}' >> $GITHUB_ENV
      - name: build Docker image
        run: |
          docker build \
            -f ./deployment/Dockerfile \
            -t ${{ env.REPO_NAME }} \
            .

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish docker image
        run: |
          version=$(.github/workflows/extract_version.sh migrations)
          docker tag ${{ env.REPO_NAME }} ghcr.io/${{ env.OWNER }}/${{ env.REPO_NAME }}:v"$version"
          docker push ghcr.io/${{ env.OWNER }}/${{ env.REPO_NAME }}:v"$version"
          docker tag ${{ env.REPO_NAME }}:v"$version" ghcr.io/${{ env.OWNER }}/${{ env.REPO_NAME }}:latest
          docker push ghcr.io/${{ env.OWNER }}/${{ env.REPO_NAME }}:latest
