name: Publish

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build docker image
        run: |
          v=$(.github/workflows/extract_version.sh migrations)
          docker build \
            -f ./deployment/Dockerfile \
            -t kant-search-database:"$v" \
            .
      - name: publish docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ env.OWNER }}/${{ env.REPO_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
