name: Publish

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: adjust env variables
        run: |
          echo "OWNER=$(echo $OWNER | awk '{print tolower($0)}')" >> $GITHUB_ENV
          echo "VERSION=$(.github/workflows/extract_version.sh migrations)" >> $GITHUB_ENV
      - name: build Docker image
        run: |
          docker build \
            -f ./deployment/Dockerfile \
            -t ${{ env.REPO_NAME }}${{ env.VERSION }} \
            .

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish docker image
        run: |
          versionImg=${{ env.REPO_NAME }}:${{ env.VERSION }}
          latestImg=${{ env.REPO_NAME }}:latest
          registry=ghcr.io/${{ env.OWNER }}
          docker tag  $versionImg $registry/$versionImg
          docker push $registry/$versionImg
          docker tag  $versionImg $registry/$latestImg
          docker push $registry/$latestImg
